name: 📝 Schema Suggestion
description: Suggest improvements or changes to entity schemas
title: "[Schema]: "
labels: ["schema", "enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a schema improvement! Your feedback helps make the entity system better for everyone.

  - type: dropdown
    id: entity-type
    attributes:
      label: Entity Type
      description: Which entity schema would you like to suggest changes to?
      options:
        - NPC (Non-Player Character)
        - Location
        - Item
        - Quest
        - Player
        - Session Summary
        - Session Prep
        - Multiple Entity Types
        - New Entity Type
    validations:
      required: true

  - type: input
    id: field-name
    attributes:
      label: Field Name (if applicable)
      description: If suggesting changes to a specific field, enter the field name
      placeholder: e.g., "importance", "faction", "type"

  - type: dropdown
    id: suggestion-type
    attributes:
      label: Suggestion Type
      description: What type of change are you suggesting?
      options:
        - Add new field
        - Modify existing field
        - Remove field
        - Change field type
        - Add new enum/option value
        - Change validation rules
        - Other
    validations:
      required: true

  - type: textarea
    id: current-schema
    attributes:
      label: Current Schema/Behavior
      description: Describe the current schema or behavior (if modifying existing)
      placeholder: |
        Current state of the schema or field:
        - Field name: importance
        - Type: enum
        - Values: minor, supporting, major

  - type: textarea
    id: proposed-change
    attributes:
      label: Proposed Change
      description: Describe the change you'd like to see
      placeholder: |
        What should be changed:
        - Add "critical" as a fourth importance level
        - Or: Add new field "alignment" with values: lawful good, neutral, chaotic evil, etc.
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why is this change needed? What problem does it solve?
      placeholder: |
        Explain why this change would be beneficial:
        - Use cases that would benefit
        - Problems with current schema
        - How it improves the system
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: What impact would this change have?
      placeholder: |
        Consider:
        - Would this be a breaking change for existing data?
        - Does this affect templates or exports?
        - Does this require UI changes?

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of how the new schema would be used
      placeholder: |
        Example usage:
        ```json
        {
          "kind": "npc",
          "title": "Volothamp Geddarm",
          "importance": "critical",  // New value
          "faction": "Harpers"
        }
        ```

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Approaches
      description: Are there other ways to achieve the same goal?
      placeholder: Describe any alternative solutions you've considered

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other information that would be helpful
      placeholder: |
        - Campaign system (D&D 5e, Pathfinder, etc.)
        - Related features or schemas
        - Screenshots or mockups

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../CONTRIBUTING.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
